create table cockpit_resort_reports (
  id int primary key not null GENERATED BY DEFAULT AS IDENTITY,
  resort_id integer,
  product_name varchar(100),
  transaction_date timestamp,
  transaction_amount_gross real,
  transaction_amount_net real,
  report_id integer
);
CREATE INDEX cockpit_resort_reports_resort_id_index ON public.cockpit_resort_reports USING btree (resort_id);
CREATE INDEX cockpit_resort_reports_transaction_date_index ON public.cockpit_resort_reports USING btree (transaction_date);